# Conda environment file used by our custom ReadTheDocs environment.
name: buzzard
dependencies:
    - python>=3.6
    - numpy>=1.16
    - scipy>=0.19.1
    - scikit-image>=0.14.1
    - gdal>=2.1.3
    - affine>=2.0.0
    - shapely>= 1.5.16
    - Rtree>=0.8.3
    - pip
    - pip:
      - opencv-python>=3.1.0
      - pint>=0.8.1
      - sortedcontainers>=1.5.9
