# Conda environment file used by our custom ReadTheDocs environment.
name: buzzard
dependencies:
    - python=3.6
    - numpy>=1.13
    - scipy>=0.19.1
    - gdal>=2.1.3
    - shapely>= 1.5.16
    - Rtree>=0.8.3
    - pip
